<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIEpxfzP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIEpxfzP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIEpxfzP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIEpxfzP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIEpxfzP\App_KernelDevDebugContainer([
    'container.build_hash' => 'IEpxfzP',
    'container.build_id' => '61c78d76',
    'container.build_time' => 1745317511,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIEpxfzP');
