services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret # paramètre obligatoire, mot de passe d'administration de mysql
      MYSQL_DATABASE: openblog
      MYSQL_USER: symfony # On met ce qu'on veut
      MYSQL_PASSWORD: symfony # On met ce qu'on veut
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build: # Fabrique une image à partir d'un Dockerfile
      context: ./php # context = endroit où se trouve Dockerfile pour PHP
    ports:
      - '8080:80' # 8080 port externe, 80 port dans l'image (EXPOSE 80)
      - '8443:443' # idem mais en https
    volumes:
        - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf # configuration apache2
        - ./apache/default-ssl.conf:/etc/apache2/sites-enabled/000-default-ssl.conf
        - ./etc/ssl:/etc/ssl
        - ./app:/var/www # ./app dossier local des fichiers php, /var/www dossier dans le conteneur
    depends_on:
        - database # Démarre APRES database
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database # Nom du service de base de données
      PMA_USER: root
      PMA_PASSWORD: secret # MYSQL_ROOT_PASSWORD
      UPLOAD_LIMIT: 20M
    ports:
      - '8899:80' # EXPOSE 80
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 #SMTP
      - 8025:8025 #Boite mail