<?php

namespace ContainerIEpxfzP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesControlleraddCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hg9z5eq.App\Controller\Admin\CategoriesController::addCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hg9z5eq.App\\Controller\\Admin\\CategoriesController::addCategory()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'translator' => ['privates', '.errored..service_locator.hg9z5eq.Symfony\\Contracts\\Translation\\TranslatableInterface', NULL, 'Cannot autowire service ".service_locator.hg9z5eq": it references interface "Symfony\\Contracts\\Translation\\TranslatableInterface" but no such service exists. Did you create an instantiable class that implements this interface?'],
        ], [
            'slugger' => '?',
            'em' => '?',
            'translator' => 'Symfony\\Contracts\\Translation\\TranslatableInterface',
        ]))->withContext('App\\Controller\\Admin\\CategoriesController::addCategory()', $container);
    }
}
