<?php

namespace ContainerIEpxfzP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploadControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\FileUploadController' shared autowired service.
     *
     * @return \App\Controller\Api\FileUploadController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/FileUploadController.php';

        return $container->services['App\\Controller\\Api\\FileUploadController'] = new \App\Controller\Api\FileUploadController(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
