<?php

namespace ContainerIEpxfzP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostsControlleraddArticleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rI9zGbN.App\Controller\Profile\PostsController::addArticle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rI9zGbN.App\\Controller\\Profile\\PostsController::addArticle()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'pictureService' => ['privates', 'App\\Service\\PictureService', 'getPictureServiceService', true],
        ], [
            'slugger' => '?',
            'em' => '?',
            'usersRepository' => 'App\\Repository\\UsersRepository',
            'pictureService' => 'App\\Service\\PictureService',
        ]))->withContext('App\\Controller\\Profile\\PostsController::addArticle()', $container);
    }
}
