<?php

namespace ContainerFkOFALc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TF0mSNsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tF0mSNs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tF0mSNs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\CategoriesController::addCategory' => ['privates', '.service_locator.hg9z5eq.App\\Controller\\Admin\\CategoriesController::addCategory()', 'getCategoriesControlleraddCategoryService', true],
            'App\\Controller\\Admin\\KeywordsController::addKeyword' => ['privates', '.service_locator.VIOnhdd.App\\Controller\\Admin\\KeywordsController::addKeyword()', 'getKeywordsControlleraddKeywordService', true],
            'App\\Controller\\MainController::index' => ['privates', '.service_locator.WO7jUZw.App\\Controller\\MainController::index()', 'getMainControllerindexService', true],
            'App\\Controller\\PostsController::index' => ['privates', '.service_locator.cv37jhs.App\\Controller\\PostsController::index()', 'getPostsControllerindexService', true],
            'App\\Controller\\PostsController::details' => ['privates', '.service_locator.cv37jhs.App\\Controller\\PostsController::details()', 'getPostsControllerdetailsService', true],
            'App\\Controller\\Profile\\PostsController::addArticle' => ['privates', '.service_locator.rI9zGbN.App\\Controller\\Profile\\PostsController::addArticle()', 'getPostsControlleraddArticleService', true],
            'App\\Controller\\Profile\\PostsController::editArticle' => ['privates', '.service_locator.awlNrV1.App\\Controller\\Profile\\PostsController::editArticle()', 'getPostsControllereditArticleService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kN4yiW2.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifUser' => ['privates', '.service_locator.1tuqeJI.App\\Controller\\RegistrationController::verifUser()', 'getRegistrationControllerverifUserService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.j6MVIfC.App\\Controller\\SecurityController::forgottenPassword()', 'getSecurityControllerforgottenPasswordService', true],
            'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.HJ19Ah3.App\\Controller\\SecurityController::resetPassword()', 'getSecurityControllerresetPasswordService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\CategoriesController:addCategory' => ['privates', '.service_locator.hg9z5eq.App\\Controller\\Admin\\CategoriesController::addCategory()', 'getCategoriesControlleraddCategoryService', true],
            'App\\Controller\\Admin\\KeywordsController:addKeyword' => ['privates', '.service_locator.VIOnhdd.App\\Controller\\Admin\\KeywordsController::addKeyword()', 'getKeywordsControlleraddKeywordService', true],
            'App\\Controller\\MainController:index' => ['privates', '.service_locator.WO7jUZw.App\\Controller\\MainController::index()', 'getMainControllerindexService', true],
            'App\\Controller\\PostsController:index' => ['privates', '.service_locator.cv37jhs.App\\Controller\\PostsController::index()', 'getPostsControllerindexService', true],
            'App\\Controller\\PostsController:details' => ['privates', '.service_locator.cv37jhs.App\\Controller\\PostsController::details()', 'getPostsControllerdetailsService', true],
            'App\\Controller\\Profile\\PostsController:addArticle' => ['privates', '.service_locator.rI9zGbN.App\\Controller\\Profile\\PostsController::addArticle()', 'getPostsControlleraddArticleService', true],
            'App\\Controller\\Profile\\PostsController:editArticle' => ['privates', '.service_locator.awlNrV1.App\\Controller\\Profile\\PostsController::editArticle()', 'getPostsControllereditArticleService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kN4yiW2.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifUser' => ['privates', '.service_locator.1tuqeJI.App\\Controller\\RegistrationController::verifUser()', 'getRegistrationControllerverifUserService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.j6MVIfC.App\\Controller\\SecurityController::forgottenPassword()', 'getSecurityControllerforgottenPasswordService', true],
            'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.HJ19Ah3.App\\Controller\\SecurityController::resetPassword()', 'getSecurityControllerresetPasswordService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\CategoriesController::addCategory' => '?',
            'App\\Controller\\Admin\\KeywordsController::addKeyword' => '?',
            'App\\Controller\\MainController::index' => '?',
            'App\\Controller\\PostsController::index' => '?',
            'App\\Controller\\PostsController::details' => '?',
            'App\\Controller\\Profile\\PostsController::addArticle' => '?',
            'App\\Controller\\Profile\\PostsController::editArticle' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifUser' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::resetPassword' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\CategoriesController:addCategory' => '?',
            'App\\Controller\\Admin\\KeywordsController:addKeyword' => '?',
            'App\\Controller\\MainController:index' => '?',
            'App\\Controller\\PostsController:index' => '?',
            'App\\Controller\\PostsController:details' => '?',
            'App\\Controller\\Profile\\PostsController:addArticle' => '?',
            'App\\Controller\\Profile\\PostsController:editArticle' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifUser' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:resetPassword' => '?',
        ]);
    }
}
