<?php

namespace ContainerFkOFALc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKeywordsControlleraddKeywordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VIOnhdd.App\Controller\Admin\KeywordsController::addKeyword()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VIOnhdd.App\\Controller\\Admin\\KeywordsController::addKeyword()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'slugger' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\KeywordsController::addKeyword()', $container);
    }
}
