<?php

namespace ContainerFkOFALc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslatableInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hg9z5eq.Symfony\Contracts\Translation\TranslatableInterface' shared service.
     *
     * @return \Symfony\Contracts\Translation\TranslatableInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hg9z5eq": it references interface "Symfony\\Contracts\\Translation\\TranslatableInterface" but no such service exists. Did you create an instantiable class that implements this interface?');
    }
}
